config/routes.rb
Rails.application.routes.draw do
  get 'users' => 'users#index', as: :user_index

  get 'users/new' => 'users#new', as: :new_user

  get 'users/:id' => 'users#show', as: :user

  get 'users/:id/edit' => 'users#edit', as: :edit_user
  
  post 'users' => 'users#create'
  put 'users/:id' => 'users#update'
  patch 'users/:id' => 'users#update'
  delete 'users/:id' => 'users#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates_uniqueness_of :name, scope: :user_id

  has_many :phones
  belongs_to :user
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact

  validates_uniqueness_of :number, scope: :contact_id

  before_save do
    if self.default_phone
      contact.phones.each do |phone|
        phone.update! default_phone: false
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
    validates_presence_of :name
    validates_uniqueness_of :name

    validates_numericality_of :age, greater_than: 0, allow_nil: true

    has_many :contacts, dependent: :restrict_with_error
    has_many :phones, through: :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update(user_params)
      redirect_to "/users"
    else
      render :new
    end
  end

  def destroy
    @user = User.find params[:id]
    if @user.destroy
      redirect_to "/users"
    else
      flash[:message] = "Fail"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/destroy.js.erb
$("#<%= @user.id %>").hide

app/views/users/edit.html.erb
<%= @user.errors.messages %>
<%= form_for @user, url: {action: "update"} do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Update" %>
<% end %>

app/views/users/index.html.erb
<%@users.each do |user|%>
    <p>
        <%= user.name%>
        <%= link_to user.name, user_path(user)%>
    </p>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<%= @user.errors.messages%>
<%= form_for @user, url: { action: "create"} do |f|%>
    <%=f.text_field :name%>
    <%= f.submit "Create"%>
<% end%>

app/views/users/show.html.erb
<%= @user.inspect %>

<%= link_to 'edit', edit_user_path(@user) %>

<%= link_to 'home',  user_index_path()%>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>